
- name: stop renting packet box
  vars: 
  packet_device:
    auth_token: "{{ packethost_auth_token }}"
    project_id: "{{ packethost_project_id }}"
    device_ids: 
    - "{{ packethost_device_id }}"
    state: absent
  delegate_to: localhost
  register: delete_reply

- name: what did packet say?
  debug: 
    var: delete_reply

# update inventory

- name: remove IP from inventory
  lineinfile:
    path: "{{ my_vars_file }}"
    regexp: 'packethost_device_ipv4:'
    line: "#packethost_device_ipv4: 1.2.3.4"
    
- name: remove device ID from inventory
  lineinfile:
    path: "{{ my_vars_file }}"
    regexp: 'packethost_device_id:'
    line: "#packethost_device_id: a23e4567-e89b-12d3-a456-426655440000"

